server:
  port: 9999

spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  session:
    store: jdbc
logging:
  level:
    org.hinbernate.SQL: DEBUG
    org.hibernate.type.description.sql: TRACE
